version: "1.0"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "rail_db"
      POSTGRES_USER: "rail"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - /Users/railsakhaviev/Documents/postgresql13/pgdata:/var/lib/postgresql/data
      - /Users/railsakhaviev/Documents/postgresql13/backup:/backup
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rail -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G