version: '1'

services:
  mysql_db:
    platform: linux/x86_64
    container_name: mysql8
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test-admin-user
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /Users/railsakhaviev/Documents/mysql/data:/var/lib/mysql
      - /Users/railsakhaviev/Documents/mysql/etc/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - '3306:3306'
