version: "1.0"
services:
  postgres:
    image: postgres:12.9
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test-admin-user"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/Users/railsakhaviev/Documents/posgresql/pgdata"
    volumes:
      - /Users/railsakhaviev/Documents/posgresql/pgdata
      - /Users/railsakhaviev/Documents/posgresql/backup
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test-admin-user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G